2022-06-26 16:44:17.319 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 16:44:17.729 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 16:44:18.188 | INFO     | __main__:<module>:264 - 
運算時間 : 1.44(S) >> 0.02(min)
2022-06-26 16:46:19.608 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 16:46:19.986 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 16:46:20.460 | INFO     | __main__:<module>:264 - 
運算時間 : 1.42(S) >> 0.02(min)
2022-06-26 16:52:26.439 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 16:52:26.760 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 16:52:27.232 | INFO     | __main__:<module>:264 - 
運算時間 : 1.23(S) >> 0.02(min)
2022-06-26 16:57:09.561 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 16:57:09.865 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 16:57:10.295 | ERROR    | __main__:<module>:44 - An error has been caught in function '<module>', process 'MainProcess' (11152), thread 'MainThread' (8036):
Traceback (most recent call last):

> File "c:\Users\JS Wang\Desktop\test\stock_xls_main.py", line 44, in <module>
    if FK_LST[0]: sub.revenue_info('https://dj.mybank.com.tw/z/zc/zch/zch_3006.djhtm')
       │          │   └ <function revenue_info at 0x000002DF623D1BD0>
       │          └ <module 'gross_sub' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_sub.py'>
       └ [1, 0, 1]

  File "c:\Users\JS Wang\Desktop\test\gross_sub.py", line 321, in revenue_info
    rev_propotions.append(cls.ProportionRevenueInfo(month,reven,mom,yoy,tyoy))
    │              │      │   │                     │     │     │   │   └ '-7.39%'
    │              │      │   │                     │     │     │   └ '-24.42%'
    │              │      │   │                     │     │     └ '-9.50%'
    │              │      │   │                     │     └ '1,575,745'
    │              │      │   │                     └ '111/05'
    │              │      │   └ <class 'gross_class.ProportionRevenueInfo'>
    │              │      └ <module 'gross_class' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_class.py'>
    │              └ <method 'append' of 'list' objects>
    └ []

  File "c:\Users\JS Wang\Desktop\test\gross_class.py", line 67, in __init__
    self.Revenue = round(float(revenue.replace(',','')/100000),2)
    │                          │       └ <method 'replace' of 'str' objects>
    │                          └ '1,575,745'
    └ <unprintable ProportionRevenueInfo object>

TypeError: unsupported operand type(s) for /: 'str' and 'int'
2022-06-26 16:57:10.431 | INFO     | __main__:<module>:264 - 
運算時間 : 1.18(S) >> 0.02(min)
2022-06-26 16:57:45.861 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 16:57:46.186 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 16:57:46.576 | ERROR    | __main__:<module>:44 - An error has been caught in function '<module>', process 'MainProcess' (6116), thread 'MainThread' (1044):
Traceback (most recent call last):

> File "c:\Users\JS Wang\Desktop\test\stock_xls_main.py", line 44, in <module>
    if FK_LST[0]: sub.revenue_info('https://dj.mybank.com.tw/z/zc/zch/zch_3006.djhtm')
       │          │   └ <function revenue_info at 0x00000299417E1BD0>
       │          └ <module 'gross_sub' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_sub.py'>
       └ [1, 0, 1]

  File "c:\Users\JS Wang\Desktop\test\gross_sub.py", line 322, in revenue_info
    rev_m.append(cls.ProportionRevenueInfo(month,reven,mom,yoy,tyoy).get_revenue())
    │     │      │   │                     │     │     │   │   └ '-7.39%'
    │     │      │   │                     │     │     │   └ '-24.42%'
    │     │      │   │                     │     │     └ '-9.50%'
    │     │      │   │                     │     └ '1,575,745'
    │     │      │   │                     └ '111/05'
    │     │      │   └ <class 'gross_class.ProportionRevenueInfo'>
    │     │      └ <module 'gross_class' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_class.py'>
    │     └ <method 'append' of 'list' objects>
    └ []

  File "c:\Users\JS Wang\Desktop\test\gross_class.py", line 80, in get_revenue
    return float((self.Revenue).replace(',',''))
                  │    └ 15.76
                  └ 111/05;15.76;-9.50%;-24.42%;-7.39%;

AttributeError: 'float' object has no attribute 'replace'
2022-06-26 16:57:46.713 | INFO     | __main__:<module>:264 - 
運算時間 : 1.15(S) >> 0.02(min)
2022-06-26 16:58:33.644 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 16:58:33.950 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 16:58:34.361 | ERROR    | __main__:<module>:44 - An error has been caught in function '<module>', process 'MainProcess' (12392), thread 'MainThread' (16800):
Traceback (most recent call last):

> File "c:\Users\JS Wang\Desktop\test\stock_xls_main.py", line 44, in <module>
    if FK_LST[0]: sub.revenue_info('https://dj.mybank.com.tw/z/zc/zch/zch_3006.djhtm')
       │          │   └ <function revenue_info at 0x000001F10D621BD0>
       │          └ <module 'gross_sub' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_sub.py'>
       └ [1, 0, 1]

  File "c:\Users\JS Wang\Desktop\test\gross_sub.py", line 322, in revenue_info
    rev_m.append(cls.ProportionRevenueInfo(month,reven,mom,yoy,tyoy).get_revenue())
    │     │      │   │                     │     │     │   │   └ '-7.39%'
    │     │      │   │                     │     │     │   └ '-24.42%'
    │     │      │   │                     │     │     └ '-9.50%'
    │     │      │   │                     │     └ '1,575,745'
    │     │      │   │                     └ '111/05'
    │     │      │   └ <class 'gross_class.ProportionRevenueInfo'>
    │     │      └ <module 'gross_class' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_class.py'>
    │     └ <method 'append' of 'list' objects>
    └ []

  File "c:\Users\JS Wang\Desktop\test\gross_class.py", line 80, in get_revenue
    return float((self.Revenue).replace(',',''))
                  │    └ 15.76
                  └ 111/05;15.76;-9.50%;-24.42%;-7.39%;

AttributeError: 'float' object has no attribute 'replace'
2022-06-26 16:58:34.512 | INFO     | __main__:<module>:264 - 
運算時間 : 1.17(S) >> 0.02(min)
2022-06-26 17:00:02.666 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 17:00:02.980 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 17:00:03.434 | ERROR    | __main__:<module>:44 - An error has been caught in function '<module>', process 'MainProcess' (13564), thread 'MainThread' (9332):
Traceback (most recent call last):

> File "c:\Users\JS Wang\Desktop\test\stock_xls_main.py", line 44, in <module>
    if FK_LST[0]: sub.revenue_info('https://dj.mybank.com.tw/z/zc/zch/zch_3006.djhtm')
       │          │   └ <function revenue_info at 0x000001EEDA941BD0>
       │          └ <module 'gross_sub' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_sub.py'>
       └ [1, 0, 1]

  File "c:\Users\JS Wang\Desktop\test\gross_sub.py", line 322, in revenue_info
    rev_m.append(cls.ProportionRevenueInfo(month,reven,mom,yoy,tyoy).get_revenue())
    │     │      │   │                     │     │     │   │   └ '-7.39%'
    │     │      │   │                     │     │     │   └ '-24.42%'
    │     │      │   │                     │     │     └ '-9.50%'
    │     │      │   │                     │     └ '1,575,745'
    │     │      │   │                     └ '111/05'
    │     │      │   └ <class 'gross_class.ProportionRevenueInfo'>
    │     │      └ <module 'gross_class' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_class.py'>
    │     └ <method 'append' of 'list' objects>
    └ []

  File "c:\Users\JS Wang\Desktop\test\gross_class.py", line 80, in get_revenue
    return float((self.Revenue).replace(',',''))
                  │    └ 15.76
                  └ 111/05;15.76;-9.50%;-24.42%;-7.39%;

AttributeError: 'float' object has no attribute 'replace'
2022-06-26 17:00:03.586 | INFO     | __main__:<module>:264 - 
運算時間 : 1.23(S) >> 0.02(min)
2022-06-26 17:02:16.946 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 17:02:17.259 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 17:02:17.704 | INFO     | __main__:<module>:264 - 
運算時間 : 1.07(S) >> 0.02(min)
2022-06-26 17:04:48.857 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 17:04:49.173 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 17:04:49.610 | ERROR    | __main__:<module>:44 - An error has been caught in function '<module>', process 'MainProcess' (12772), thread 'MainThread' (13892):
Traceback (most recent call last):

> File "c:\Users\JS Wang\Desktop\test\stock_xls_main.py", line 44, in <module>
    if FK_LST[0]: sub.revenue_info('https://dj.mybank.com.tw/z/zc/zch/zch_3006.djhtm')
       │          │   └ <function revenue_info at 0x000001BBB49A5B40>
       │          └ <module 'gross_sub' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_sub.py'>
       └ [1, 0, 1]

  File "c:\Users\JS Wang\Desktop\test\gross_sub.py", line 322, in revenue_info
    rev_propotions[1] = cls.ProportionRevenueInfo.get_revenue_100m()
    │                   │   │                     └ <function ProportionRevenueInfo.get_revenue_100m at 0x000001BBB499A710>
    │                   │   └ <class 'gross_class.ProportionRevenueInfo'>
    │                   └ <module 'gross_class' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_class.py'>
    └ [111/05;1,575,745;-9.50%;-24.42%;-7.39%;]

TypeError: ProportionRevenueInfo.get_revenue_100m() missing 1 required positional argument: 'self'
2022-06-26 17:04:49.715 | INFO     | __main__:<module>:264 - 
運算時間 : 1.15(S) >> 0.02(min)
2022-06-26 17:09:56.539 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 17:09:56.828 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 17:09:57.222 | ERROR    | __main__:<module>:44 - An error has been caught in function '<module>', process 'MainProcess' (1516), thread 'MainThread' (7292):
Traceback (most recent call last):

> File "c:\Users\JS Wang\Desktop\test\stock_xls_main.py", line 44, in <module>
    if FK_LST[0]: sub.revenue_info('https://dj.mybank.com.tw/z/zc/zch/zch_3006.djhtm')
       │          │   └ <function revenue_info at 0x0000020C9B2DDB40>
       │          └ <module 'gross_sub' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_sub.py'>
       └ [1, 0, 1]

  File "c:\Users\JS Wang\Desktop\test\gross_sub.py", line 308, in revenue_info
    prop = cls.ProportionRevenueInfo()
           │   └ <class 'gross_class.ProportionRevenueInfo'>
           └ <module 'gross_class' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_class.py'>

TypeError: ProportionRevenueInfo.__init__() missing 5 required positional arguments: 'month', 'revenue', 'mom', 'yoy', and 'total_yoy'
2022-06-26 17:09:57.300 | INFO     | __main__:<module>:264 - 
運算時間 : 1.06(S) >> 0.02(min)
2022-06-26 17:11:50.366 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 17:11:50.658 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 17:11:51.071 | ERROR    | __main__:<module>:44 - An error has been caught in function '<module>', process 'MainProcess' (5004), thread 'MainThread' (6704):
Traceback (most recent call last):

> File "c:\Users\JS Wang\Desktop\test\stock_xls_main.py", line 44, in <module>
    if FK_LST[0]: sub.revenue_info('https://dj.mybank.com.tw/z/zc/zch/zch_3006.djhtm')
       │          │   └ <function revenue_info at 0x0000020E94855B40>
       │          └ <module 'gross_sub' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_sub.py'>
       └ [1, 0, 1]

  File "c:\Users\JS Wang\Desktop\test\gross_sub.py", line 323, in revenue_info
    rev_propotions[1] = prop.get_revenue_100m()
    │                   │    └ <function ProportionRevenueInfo.get_revenue_100m at 0x0000020E9484A710>
    │                   └ 111/05;1,575,745;-9.50%;-24.42%;-7.39%;
    └ ['111/05;1,575,745;-9.50%;-24.42%;-7.39%;']

IndexError: list assignment index out of range
2022-06-26 17:11:51.159 | INFO     | __main__:<module>:264 - 
運算時間 : 1.13(S) >> 0.02(min)
2022-06-26 17:14:07.314 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 17:14:07.608 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 17:14:08.018 | INFO     | __main__:<module>:264 - 
運算時間 : 1.03(S) >> 0.02(min)
2022-06-26 17:14:54.135 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 17:14:54.420 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 17:14:54.858 | INFO     | __main__:<module>:264 - 
運算時間 : 1.04(S) >> 0.02(min)
2022-06-26 17:24:43.217 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 17:24:43.604 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 17:24:44.062 | ERROR    | __main__:<module>:44 - An error has been caught in function '<module>', process 'MainProcess' (4272), thread 'MainThread' (900):
Traceback (most recent call last):

> File "c:\Users\JS Wang\Desktop\test\stock_xls_main.py", line 44, in <module>
    if FK_LST[0]: sub.revenue_info('https://dj.mybank.com.tw/z/zc/zch/zch_3006.djhtm')
       │          │   └ <function revenue_info at 0x000001FF53D25B40>
       │          └ <module 'gross_sub' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_sub.py'>
       └ [1, 0, 1]

  File "c:\Users\JS Wang\Desktop\test\gross_sub.py", line 325, in revenue_info
    rev_propotions[0][1] = prop.get_revenue_100m()
    │                      │    └ <function ProportionRevenueInfo.get_revenue_100m at 0x000001FF53D1E710>
    │                      └ 111/05;1,575,745;-9.50%;-24.42%;-7.39%;
    └ ['111/05;1,575,745;-9.50%;-24.42%;-7.39%;']

TypeError: 'str' object does not support item assignment
2022-06-26 17:24:44.128 | INFO     | __main__:<module>:264 - 
運算時間 : 1.29(S) >> 0.02(min)
2022-06-26 17:30:20.444 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 17:30:20.846 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 17:30:21.293 | ERROR    | __main__:<module>:44 - An error has been caught in function '<module>', process 'MainProcess' (17804), thread 'MainThread' (18004):
Traceback (most recent call last):

> File "c:\Users\JS Wang\Desktop\test\stock_xls_main.py", line 44, in <module>
    if FK_LST[0]: sub.revenue_info('https://dj.mybank.com.tw/z/zc/zch/zch_3006.djhtm')
       │          │   └ <function revenue_info at 0x000001F0ED255AB0>
       │          └ <module 'gross_sub' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_sub.py'>
       └ [1, 0, 1]

  File "c:\Users\JS Wang\Desktop\test\gross_sub.py", line 350, in revenue_info
    for i in range(len(rev_propotions)): STK_REV.append(rev_propotions[0][i])
        │              │                 │       │      │                 └ 5
        │              │                 │       │      └ [['111/05', 19.40898, '-9.50%', '-24.42%', '-7.39%'], ['111/04', '1,741,074', '-4.39%', '-13.45%', '-2.30%'], ['111/03', '1,8...
        │              │                 │       └ <method 'append' of 'list' objects>
        │              │                 └ [-8.0, -7.0, 'DEC -3', '111/05', 19.40898, '-9.50%', '-24.42%', '-7.39%']
        │              └ [['111/05', 19.40898, '-9.50%', '-24.42%', '-7.39%'], ['111/04', '1,741,074', '-4.39%', '-13.45%', '-2.30%'], ['111/03', '1,8...
        └ 5

IndexError: list index out of range
2022-06-26 17:30:21.409 | INFO     | __main__:<module>:264 - 
運算時間 : 1.33(S) >> 0.02(min)
2022-06-26 17:31:02.366 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 17:31:02.654 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 17:31:03.113 | INFO     | __main__:<module>:264 - 
運算時間 : 1.08(S) >> 0.02(min)
2022-06-26 17:32:26.759 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 17:32:27.087 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 17:32:27.545 | ERROR    | __main__:<module>:44 - An error has been caught in function '<module>', process 'MainProcess' (5048), thread 'MainThread' (856):
Traceback (most recent call last):

> File "c:\Users\JS Wang\Desktop\test\stock_xls_main.py", line 44, in <module>
    if FK_LST[0]: sub.revenue_info('https://dj.mybank.com.tw/z/zc/zch/zch_3006.djhtm')
       │          │   └ <function revenue_info at 0x000001EE1D4E5B40>
       │          └ <module 'gross_sub' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_sub.py'>
       └ [1, 0, 1]

  File "c:\Users\JS Wang\Desktop\test\gross_sub.py", line 325, in revenue_info
    if tr == trs[9]: rev_propotions[0][1] = prop.get_revenue_100m()
       │     │       │                      │    └ <function ProportionRevenueInfo.get_revenue_100m at 0x000001EE1D4DA710>
       │     │       │                      └ <unprintable ProportionRevenueInfo object>
       │     │       └ [['111/05', '1,575,745', '-9.50%', '-24.42%', '-7.39%']]
       │     └ [[<tr>], [<tr>], [<tr>], [<tr>], [<tr>], [<tr>], [<tr>]]
       └ [<tr>]

IndexError: list index out of range
2022-06-26 17:32:27.688 | INFO     | __main__:<module>:264 - 
運算時間 : 1.27(S) >> 0.02(min)
2022-06-26 17:34:38.372 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 17:34:38.777 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 17:34:39.234 | INFO     | __main__:<module>:264 - 
運算時間 : 1.2(S) >> 0.02(min)
2022-06-26 17:36:37.422 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 17:36:37.770 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 17:36:38.233 | INFO     | __main__:<module>:264 - 
運算時間 : 1.28(S) >> 0.02(min)
2022-06-26 17:47:41.180 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 17:47:41.508 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 17:47:41.978 | ERROR    | __main__:<module>:44 - An error has been caught in function '<module>', process 'MainProcess' (3212), thread 'MainThread' (15140):
Traceback (most recent call last):

> File "c:\Users\JS Wang\Desktop\test\stock_xls_main.py", line 44, in <module>
    if FK_LST[0]: sub.dayily_info('https://dj.mybank.com.tw/z/zc/zch/zch_3006.djhtm')
       │          │   └ <function dayily_info at 0x00000276A38757E0>
       │          └ <module 'gross_sub' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_sub.py'>
       └ [1, 0, 1]

  File "c:\Users\JS Wang\Desktop\test\gross_sub.py", line 265, in dayily_info
    op_price = float((tds0[1].text().strip()).replace(',',''))
                      └ [[<td.t3n0>]]

IndexError: list index out of range
2022-06-26 17:47:42.088 | INFO     | __main__:<module>:264 - 
運算時間 : 1.24(S) >> 0.02(min)
2022-06-26 17:48:40.541 | SUCCESS  | gross_sub:get_stock_datetime:34 - REQS: success
2022-06-26 17:48:40.712 | SUCCESS  | gross_sub:check_reqs_data:230 - REQS: success.
2022-06-26 17:48:41.170 | INFO     | gross_sub:dayily_info:294 - Today:
積體電路(IC)100.00% (2021年);5.13;109600.0;2759.0;10283.0;3.59;28.62;2.1;213.0;94.7;99.5;97.4;
2022-06-26 17:48:41.189 | INFO     | __main__:<module>:264 - 
運算時間 : 0.97(S) >> 0.02(min)
2022-06-26 18:03:02.495 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 18:03:02.742 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 18:03:03.119 | INFO     | __main__:<module>:264 - 
運算時間 : 0.96(S) >> 0.02(min)
2022-06-26 18:04:14.447 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 18:04:15.060 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 18:04:15.478 | INFO     | __main__:<module>:264 - 
運算時間 : 1.35(S) >> 0.02(min)
2022-06-26 18:05:51.207 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 18:05:51.421 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 18:05:51.787 | INFO     | __main__:<module>:264 - 
運算時間 : 0.88(S) >> 0.01(min)
2022-06-26 18:07:08.748 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 18:07:08.938 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 18:07:09.302 | INFO     | __main__:<module>:264 - 
運算時間 : 0.89(S) >> 0.01(min)
2022-06-26 18:11:09.923 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 18:11:10.137 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 18:11:10.489 | INFO     | __main__:<module>:264 - 
運算時間 : 0.92(S) >> 0.02(min)
2022-06-26 18:16:19.278 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 18:16:19.469 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 18:16:19.851 | INFO     | __main__:<module>:264 - 
運算時間 : 0.87(S) >> 0.01(min)
2022-06-26 18:27:35.417 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 18:27:35.644 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 18:27:36.036 | ERROR    | __main__:<module>:44 - An error has been caught in function '<module>', process 'MainProcess' (1644), thread 'MainThread' (7584):
Traceback (most recent call last):

> File "c:\Users\JS Wang\Desktop\test\stock_xls_main.py", line 44, in <module>
    if FK_LST[0]: sub.counter_info('http://jsjustweb.jihsun.com.tw/z/zc/zcl/zcl_3006.djhtm')#sub.revenue_info('https://dj.mybank.com.tw/z/zc/zch/zch_3006.djhtm')
       │          │   └ <function counter_info at 0x0000014A66299EA0>
       │          └ <module 'gross_sub' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_sub.py'>
       └ [1, 0, 1]

  File "c:\Users\JS Wang\Desktop\test\gross_sub.py", line 376, in counter_info
    counter_lst[tr.index()] = [ tds[i].text().strip() for i in range(len(tds)) \
    │           │  │            │                                        └ [[<td.t3n0>], [<td.t3n1>], [<td.t3n1>], [<td.t3n1>], [<td.t3n1>], [<td.t3n1>], [<td.t3n1>], [<td.t3n1>], [<td.t3n1>], [<td.t3...
    │           │  │            └ [[<td.t3n0>], [<td.t3n1>], [<td.t3n1>], [<td.t3n1>], [<td.t3n1>], [<td.t3n1>], [<td.t3n1>], [<td.t3n1>], [<td.t3n1>], [<td.t3...
    │           │  └ <method 'index' of 'list' objects>
    │           └ [<tr>]
    └ [0, 0, 0, 0, 0, 0]

TypeError: index expected at least 1 argument, got 0
2022-06-26 18:27:36.189 | INFO     | __main__:<module>:264 - 
運算時間 : 1.09(S) >> 0.02(min)
2022-06-26 18:29:42.543 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 18:29:42.767 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 18:29:43.620 | INFO     | __main__:<module>:264 - 
運算時間 : 1.4(S) >> 0.02(min)
2022-06-26 19:54:58.924 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 19:54:59.144 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 19:54:59.532 | INFO     | __main__:<module>:264 - 
運算時間 : 1.01(S) >> 0.02(min)
2022-06-26 20:58:46.604 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 20:58:47.174 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 20:58:48.138 | INFO     | __main__:<module>:264 - 
運算時間 : 1.94(S) >> 0.03(min)
2022-06-26 21:01:25.909 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 21:01:26.204 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 21:01:26.580 | INFO     | __main__:<module>:264 - 
運算時間 : 0.99(S) >> 0.02(min)
2022-06-26 21:15:45.422 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 21:15:45.625 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 21:15:46.003 | INFO     | __main__:<module>:264 - 
運算時間 : 0.96(S) >> 0.02(min)
2022-06-26 21:30:21.305 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 21:30:21.573 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 21:30:22.225 | ERROR    | __main__:<module>:44 - An error has been caught in function '<module>', process 'MainProcess' (9604), thread 'MainThread' (9140):
Traceback (most recent call last):

> File "c:\Users\JS Wang\Desktop\test\stock_xls_main.py", line 44, in <module>
    if FK_LST[0]: sub.counter_info('http://jsjustweb.jihsun.com.tw/z/zc/zcl/zcl_3006.djhtm')#sub.revenue_info('https://dj.mybank.com.tw/z/zc/zch/zch_3006.djhtm')
       │          │   └ <function counter_info at 0x000001E169F96050>
       │          └ <module 'gross_sub' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_sub.py'>
       └ [1, 0, 1]

  File "c:\Users\JS Wang\Desktop\test\gross_sub.py", line 385, in counter_info
    print(prop.get_cnt_sort())
          │    └ <function ProportionCounterInfo.get_cnt_sort at 0x000001E169F92950>
          └ <gross_class.ProportionCounterInfo object at 0x000001E16A17B7F0>

  File "c:\Users\JS Wang\Desktop\test\gross_class.py", line 100, in get_cnt_sort
    sort_lst = [ tmp[i][j] for i in range(len(tmp)) for j in range(tmp[i]) if j in range(4)]
                 │                            │                    └ [['486', '0', '311', '797', '14.43%'], ['-719', '0', '1021', '302', '14.23%'], ['-1923', '4', '11', '-1908', '14.20%'], ['200...
                 │                            └ [['486', '0', '311', '797', '14.43%'], ['-719', '0', '1021', '302', '14.23%'], ['-1923', '4', '11', '-1908', '14.20%'], ['200...
                 └ [['486', '0', '311', '797', '14.43%'], ['-719', '0', '1021', '302', '14.23%'], ['-1923', '4', '11', '-1908', '14.20%'], ['200...

  File "c:\Users\JS Wang\Desktop\test\gross_class.py", line 100, in <listcomp>
    sort_lst = [ tmp[i][j] for i in range(len(tmp)) for j in range(tmp[i]) if j in range(4)]
                 │   │         │              │                    │   └ 0
                 │   │         │              │                    └ [['486', '0', '311', '797', '14.43%'], ['-719', '0', '1021', '302', '14.23%'], ['-1923', '4', '11', '-1908', '14.20%'], ['200...
                 │   │         │              └ [['486', '0', '311', '797', '14.43%'], ['-719', '0', '1021', '302', '14.23%'], ['-1923', '4', '11', '-1908', '14.20%'], ['200...
                 │   │         └ 0
                 │   └ 0
                 └ [['486', '0', '311', '797', '14.43%'], ['-719', '0', '1021', '302', '14.23%'], ['-1923', '4', '11', '-1908', '14.20%'], ['200...

TypeError: 'list' object cannot be interpreted as an integer
2022-06-26 21:30:22.425 | INFO     | __main__:<module>:264 - 
運算時間 : 1.5(S) >> 0.03(min)
2022-06-26 21:31:33.666 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 21:31:33.979 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 21:31:34.340 | ERROR    | __main__:<module>:44 - An error has been caught in function '<module>', process 'MainProcess' (4376), thread 'MainThread' (9340):
Traceback (most recent call last):

> File "c:\Users\JS Wang\Desktop\test\stock_xls_main.py", line 44, in <module>
    if FK_LST[0]: sub.counter_info('http://jsjustweb.jihsun.com.tw/z/zc/zcl/zcl_3006.djhtm')#sub.revenue_info('https://dj.mybank.com.tw/z/zc/zch/zch_3006.djhtm')
       │          │   └ <function counter_info at 0x000002035CB72170>
       │          └ <module 'gross_sub' from 'c:\\Users\\JS Wang\\Desktop\\test\\gross_sub.py'>
       └ [1, 0, 1]

  File "c:\Users\JS Wang\Desktop\test\gross_sub.py", line 385, in counter_info
    print(prop.get_cnt_sort())
          │    └ <function ProportionCounterInfo.get_cnt_sort at 0x000002035CB6EA70>
          └ <gross_class.ProportionCounterInfo object at 0x000002035CD6B640>

  File "c:\Users\JS Wang\Desktop\test\gross_class.py", line 100, in get_cnt_sort
    sort_lst = [ tmp[i][j] for i in range(len(tmp)) for j in range(tmp[i])]
                 │                            │                    └ [['486', '0', '311', '797', '14.43%'], ['-719', '0', '1021', '302', '14.23%'], ['-1923', '4', '11', '-1908', '14.20%'], ['200...
                 │                            └ [['486', '0', '311', '797', '14.43%'], ['-719', '0', '1021', '302', '14.23%'], ['-1923', '4', '11', '-1908', '14.20%'], ['200...
                 └ [['486', '0', '311', '797', '14.43%'], ['-719', '0', '1021', '302', '14.23%'], ['-1923', '4', '11', '-1908', '14.20%'], ['200...

  File "c:\Users\JS Wang\Desktop\test\gross_class.py", line 100, in <listcomp>
    sort_lst = [ tmp[i][j] for i in range(len(tmp)) for j in range(tmp[i])]
                 │   │         │              │                    │   └ 0
                 │   │         │              │                    └ [['486', '0', '311', '797', '14.43%'], ['-719', '0', '1021', '302', '14.23%'], ['-1923', '4', '11', '-1908', '14.20%'], ['200...
                 │   │         │              └ [['486', '0', '311', '797', '14.43%'], ['-719', '0', '1021', '302', '14.23%'], ['-1923', '4', '11', '-1908', '14.20%'], ['200...
                 │   │         └ 0
                 │   └ 0
                 └ [['486', '0', '311', '797', '14.43%'], ['-719', '0', '1021', '302', '14.23%'], ['-1923', '4', '11', '-1908', '14.20%'], ['200...

TypeError: 'list' object cannot be interpreted as an integer
2022-06-26 21:31:34.524 | INFO     | __main__:<module>:264 - 
運算時間 : 1.18(S) >> 0.02(min)
2022-06-26 21:32:10.667 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 21:32:10.842 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 21:32:11.199 | INFO     | __main__:<module>:264 - 
運算時間 : 0.84(S) >> 0.01(min)
2022-06-26 21:33:33.209 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 21:33:33.379 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 21:33:33.727 | INFO     | __main__:<module>:264 - 
運算時間 : 0.83(S) >> 0.01(min)
2022-06-26 22:26:59.012 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 22:26:59.256 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 22:26:59.627 | INFO     | __main__:<module>:264 - 
運算時間 : 0.9(S) >> 0.02(min)
2022-06-26 22:32:52.105 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 22:32:52.300 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 22:32:52.682 | INFO     | __main__:<module>:264 - 
運算時間 : 0.93(S) >> 0.02(min)
2022-06-26 22:34:35.000 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 22:34:35.167 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 22:34:35.534 | INFO     | __main__:<module>:264 - 
運算時間 : 0.86(S) >> 0.01(min)
2022-06-26 22:35:48.868 | SUCCESS  | gross_sub:get_stock_datetime:35 - REQS: success
2022-06-26 22:35:49.118 | SUCCESS  | gross_sub:check_reqs_data:231 - REQS: success.
2022-06-26 22:35:49.516 | INFO     | __main__:<module>:264 - 
運算時間 : 0.96(S) >> 0.02(min)
